"""blacklist

Revision ID: 8469210ba934
Revises: c7f69900f278
Create Date: 2025-10-31 16:52:22.074654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8469210ba934'
down_revision: Union[str, Sequence[str], None] = 'c7f69900f278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackList',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jwt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackList')
    # ### end Alembic commands ###
